"""
Thin pipeline runner for new essay input.

This file is meant to stay small and mostly call functions that already
exist in the other scripts.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from add_to_database import update_database
from add_to_database import PROCESSED_INPUT_DIR
from export_docs_to_txt import export_new_docs
from sync_drive import run_sync, get_creds


SCRIPT_DIR = Path(__file__).resolve().parent
BACKEND_DIR = SCRIPT_DIR.parent
DATABASE_JSONL = BACKEND_DIR / "drive_data/finalized_data_jsonl/database.jsonl"
EMBED_JSONL = BACKEND_DIR / "drive_data/embed_output/embed.jsonl"
UPLOAD_TEST_DIR = BACKEND_DIR / "drive_data/upload_test_samples"

load_dotenv()
DRIVE_FOLDER_ID = os.getenv("DRIVE_FOLDER_ID", "")

# helper function to get the file type
def get_mimetype(path: Path) -> str:
    suffix = path.suffix.lower()

    if suffix == ".txt":
        return "text/plain"
    elif suffix in [".json", ".jsonl"]:
        return "application/json"
    elif suffix == ".png":
        return "image/png"
    elif suffix in [".jpg", ".jpeg"]:
        return "image/jpeg"
    elif suffix == ".pdf":
        return "application/pdf"
    else:
        return "application/octet-stream"
    

# general function uploading files to google drive
def upload_to_drive(file_paths: list[Path]) -> None:
    if not DRIVE_FOLDER_ID:
        print("Skipping upload: DRIVE_FOLDER_ID is empty or invalid.")
        return

    existing_paths = [Path(path) for path in file_paths if Path(path).exists() and Path(path).is_file()]
    missing_paths = [str(path) for path in file_paths if not Path(path).exists()]

    if missing_paths:
        print(f"Skipping {len(missing_paths)} missing file(s).")

    if not existing_paths:
        print("Skipping upload: no valid files were provided.")
        return
    
    creds = get_creds()
    service = build("drive", "v3", credentials=creds)

    # Get existing files in Drive folder
    response = service.files().list(
        q=f"'{DRIVE_FOLDER_ID}' in parents and trashed=false",
        fields="files(id,name)",
        pageSize=1000,
    ).execute()

    existing_files = {
        item["name"]: item["id"]
        for item in response.get("files", [])
    }

    uploaded_count = 0
    updated_count = 0

    for path in existing_paths:
        try:
            media = MediaFileUpload(str(path), mimetype=get_mimetype(path))

            if path.name in existing_files:
                service.files().update(
                    fileId=existing_files[path.name],
                    media_body=media,
                ).execute()
                updated_count += 1
                print(f"Updated: {path.name}")
            else:
                created = service.files().create(
                    body={"name": path.name, "parents": [DRIVE_FOLDER_ID]},
                    media_body=media,
                    fields="id",
                ).execute()
                existing_files[path.name] = created["id"]
                uploaded_count += 1
                print(f"Uploaded: {path.name}")

        except Exception as e:
            print(f"Failed to upload {path.name}: {e}")

    print(f"Upload complete. Created {uploaded_count}, updated {updated_count}.")

def organize_new_input() -> None:
    if not PROCESSED_INPUT_DIR.exists():
        print(f"Processed folder not found: {PROCESSED_INPUT_DIR}")
        return

    try:
        txt_files = [
            f for f in PROCESSED_INPUT_DIR.rglob("*")
            if f.is_file() and f.suffix.lower() == ".txt"
        ]
    except Exception as e:
        print(f"Error reading files: {e}")
        return

    if not txt_files:
        print("No .txt files found to upload.")
        return

    upload_to_drive(txt_files)


def create_upload_test_files() -> list[Path]:
    """
    Create a few local sample files for manual upload testing.
    These live outside the real input/processed pipeline folders.
    """
    UPLOAD_TEST_DIR.mkdir(parents=True, exist_ok=True)

    txt_path = UPLOAD_TEST_DIR / "sample_upload_test.txt"
    jsonl_path = UPLOAD_TEST_DIR / "sample_upload_test.jsonl"

    txt_path.write_text(
        "prompt: Upload test prompt\n"
        "content: This is a safe local upload test file generated by run_new_input.py.\n",
        encoding="utf-8",
    )
    jsonl_path.write_text(
        '{"kind":"upload_test","note":"Safe sample file for Google Drive upload testing."}\n',
        encoding="utf-8",
    )

    print(f"Created test files in {UPLOAD_TEST_DIR}")
    return [txt_path, jsonl_path]


def run_new_input() -> None:
    print("\n=== Export new docs from Google Drive ===")
    export_new_docs()

    print("\n=== Add new txt files into database.jsonl and move new input files to the processed folder ===")
    update_database()

    print("\n=== Upload processed new input files back to Google Drive ===")
    organize_new_input()

    print("\n== Upload updated database.jsonl and embed.jsonl to Google Drive===")
    jsonl_files = [DATABASE_JSONL, EMBED_JSONL]
    upload_to_drive(jsonl_files)

    print("\n=== Sync processed folder down locally ===")
    if not DRIVE_FOLDER_ID:
        print("Skipping sync-down: DRIVE_FOLDER_ID is empty or invalid.")
    else:
        run_sync(DRIVE_FOLDER_ID, BACKEND_DIR)

    print("\n Finish syncing new input ✅")


if __name__ == "__main__":
    run_new_input()
